version: 0.8.3.{build}
branches:
  only:
  - master
  
image:
  - Visual Studio 2015

configuration:
  - Debug
  - Release
  
platform:
  - Win32
  - x64

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  GENERATOR: Visual Studio 14 2015
  MSVC: 14.0
  RTTR_DISABLE_ASSERT_BREAKPOINT: 1

install:
  - dir C:\Libraries
  - appveyor-retry git submodule update --init
  - cd contrib
  - 7z x full-contrib-msvc.rar
  - cd ..

before_build:
  - cd build
  - if %platform% == Win32 (set BOOST_LIBDIR=lib32-msvc-%MSVC%) else ((set BOOST_LIBDIR=lib64-msvc-%MSVC%) && (set GENERATOR=%GENERATOR% Win64))
  - echo "Configuring %GENERATOR% for %configuration% on %platform% with boost=%BOOST_ROOT%\%BOOST_LIBDIR%"
  - cmake -G "%GENERATOR%" -DRTTR_ENABLE_WERROR=ON -DBOOST_LIBRARYDIR="%BOOST_ROOT%\%BOOST_LIBDIR%" ..
  - cd ..
    
build:

build_script:
  - echo "Building for %configuration% on %platform%"
  - msbuild /m /p:Configuration="%configuration%" /p:Platform="%platform%" /v:n build/s25client.sln

test_script:
  - cd build
  - ctest --output-on-failure -C %configuration%
  - cd ..
