name: Static analysis

on:
  push:
  pull_request:

env:
  CC: clang-9
  CXX: clang++-9
  ADDITIONAL_CMAKE_FLAGS:

jobs:
  StyleAndFormatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init
    - name: Validation
      run: tools/ci/staticValidation.sh "$GITHUB_WORKSPACE"
    - name: Formatting
      uses: Flamefire/clang-format-lint-action@master
      with:
        source: 'extras libs tests external/libendian external/liblobby external/libsiedler2 external/libutil external/mygettext external/s25edit external/s25update'
        clangFormatVersion: 9
    - name: Lint markdown files
      uses: avto-dev/markdown-lint@v1.3.0
      with:
        args:  --ignore data/RTTR/MAPS .
        ignore: external

  Clang-Tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          clang-9 clang-tidy-9 \
          libsdl2-dev libsdl2-mixer-dev libcurl4-openssl-dev libbz2-dev libminiupnpc-dev liblua5.2-dev gettext \
          libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libboost-test-dev libboost-locale-dev libboost-iostreams-dev
    - name: Clang-Tidy Main
      run: tools/ci/runClangTidy.sh main
    - name: Clang-Tidy External
      run: tools/ci/runClangTidy.sh external
